version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production